<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<div "result">I launch Calculator Application (PASSED : 3s)</div>]]>
    </line>
    <line>
      <![CDATA[<div "result">I enter number as &quot;16&quot; in calculator (PASSED : 9s)</div>]]>
    </line>
    <line>
      <![CDATA[<div "result">I click on &quot;SQUAREROOT&quot; in calculator (PASSED : 0s)</div>]]>
    </line>
    <line>
      <![CDATA[<div "result">I click on &quot;EQUAL&quot; in calculator (PASSED : 0s)</div>]]>
    </line>
    <line>
      <![CDATA[<div "result">I validate the result as &quot;4&quot; in calculator (FAILED : 0s)</div>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="14411" started-at="2020-07-21T06:19:57Z" finished-at="2020-07-21T06:20:11Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:runner.TestRunner@6b143ee9]" name="runScenario" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Test" duration-ms="14411" started-at="2020-07-21T06:19:57Z" finished-at="2020-07-21T06:20:11Z">
      <class name="runner.TestRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:runner.TestRunner@6b143ee9]" name="setUpClass" is-config="true" duration-ms="189" started-at="2020-07-21T06:19:57Z" finished-at="2020-07-21T06:19:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="runScenario(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:runner.TestRunner@6b143ee9]" name="runScenario" duration-ms="14088" started-at="2020-07-21T06:19:57Z" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2020-07-21T06:20:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate Square Root to be performed in Calculator"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["BOT 3594 Automation QA Engineer Interview Task"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4] but found [Display is 1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4] but found [Display is 1]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at core.WinniumSteps.verifyResult(WinniumSteps.java:71)
at âœ½.I validate the result as "4" in calculator(src/test/resources/feature/desktop/Calculator.feature:11)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<div "result">I launch Calculator Application (PASSED : 3s)</div>]]>
            </line>
            <line>
              <![CDATA[<div "result">I enter number as &quot;16&quot; in calculator (PASSED : 9s)</div>]]>
            </line>
            <line>
              <![CDATA[<div "result">I click on &quot;SQUAREROOT&quot; in calculator (PASSED : 0s)</div>]]>
            </line>
            <line>
              <![CDATA[<div "result">I click on &quot;EQUAL&quot; in calculator (PASSED : 0s)</div>]]>
            </line>
            <line>
              <![CDATA[<div "result">I validate the result as &quot;4&quot; in calculator (FAILED : 0s)</div>]]>
            </line>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method status="FAIL" signature="closeDriver()[pri:0, instance:runner.TestRunner@6b143ee9]" name="closeDriver" is-config="true" duration-ms="1" started-at="2020-07-21T06:20:11Z" finished-at="2020-07-21T06:20:11Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at core.Context.closeDriver(Context.java:192)
at runner.TestRunner.closeDriver(TestRunner.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:runner.TestRunner@6b143ee9]" name="tearDownClass" is-config="true" duration-ms="59" started-at="2020-07-21T06:20:11Z" finished-at="2020-07-21T06:20:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- runner.TestRunner -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
